#pragma once

#include "qdefines.h"
#include "qrecorder_i.h"

#define EXPLICIT_INSTANTATION_FUNC1(name,T) \
template qscalar<T> VSGRAPH_API name(const qscalar<T>& rhs);

#ifdef INSTANTIATE_AVX512
#define EXPLICIT_INSTANTATION_FUNC1_ALL(name) \
EXPLICIT_INSTANTATION_FUNC1(name,double) \
EXPLICIT_INSTANTATION_FUNC1(name,float) \
EXPLICIT_INSTANTATION_FUNC1(name,__m512d) \
EXPLICIT_INSTANTATION_FUNC1(name,__m512) \
EXPLICIT_INSTANTATION_FUNC1(name,__m256d) \
EXPLICIT_INSTANTATION_FUNC1(name,__m256) \
EXPLICIT_INSTANTATION_FUNC1(name,__m128d) \
EXPLICIT_INSTANTATION_FUNC1(name,__m128) 
#else
#define EXPLICIT_INSTANTATION_FUNC1_ALL(name) \
EXPLICIT_INSTANTATION_FUNC1(name,double) \
EXPLICIT_INSTANTATION_FUNC1(name,float) \
EXPLICIT_INSTANTATION_FUNC1(name,__m256d) \
EXPLICIT_INSTANTATION_FUNC1(name,__m256) \
EXPLICIT_INSTANTATION_FUNC1(name,__m128d) \
EXPLICIT_INSTANTATION_FUNC1(name,__m128) 
#endif

#define EXPLICIT_INSTANTATION_FUNC21(name,T) \
template qscalar<T> VSGRAPH_API name(const qscalar<T>& lhs, const qscalar<T>& rhs);

#ifdef INSTANTIATE_AVX512
#define EXPLICIT_INSTANTATION_FUNC21_ALL(name) \
EXPLICIT_INSTANTATION_FUNC21(name,double) \
EXPLICIT_INSTANTATION_FUNC21(name,float) \
EXPLICIT_INSTANTATION_FUNC21(name,__m512d) \
EXPLICIT_INSTANTATION_FUNC21(name,__m512) \
EXPLICIT_INSTANTATION_FUNC21(name,__m256d) \
EXPLICIT_INSTANTATION_FUNC21(name,__m256) \
EXPLICIT_INSTANTATION_FUNC21(name,__m128d) \
EXPLICIT_INSTANTATION_FUNC21(name,__m128) 
#else
#define EXPLICIT_INSTANTATION_FUNC21_ALL(name) \
EXPLICIT_INSTANTATION_FUNC21(name,double) \
EXPLICIT_INSTANTATION_FUNC21(name,float) \
EXPLICIT_INSTANTATION_FUNC21(name, __m256d) \
EXPLICIT_INSTANTATION_FUNC21(name, __m256) \
EXPLICIT_INSTANTATION_FUNC21(name, __m128d) \
EXPLICIT_INSTANTATION_FUNC21(name, __m128)
#endif

#define EXPLICIT_INSTANTATION_FUNC22(name,T) \
template qscalar<T> VSGRAPH_API name(const qscalar<T>& lhs, const qnumber<typename number_traits<T>::type>& rhs);

#ifdef INSTANTIATE_AVX512
#define EXPLICIT_INSTANTATION_FUNC22_ALL(name) \
EXPLICIT_INSTANTATION_FUNC22(name,double) \
EXPLICIT_INSTANTATION_FUNC22(name,float) \
EXPLICIT_INSTANTATION_FUNC22(name,__m512d) \
EXPLICIT_INSTANTATION_FUNC22(name,__m512) \
EXPLICIT_INSTANTATION_FUNC22(name,__m256d) \
EXPLICIT_INSTANTATION_FUNC22(name,__m256) \
EXPLICIT_INSTANTATION_FUNC22(name,__m128d) \
EXPLICIT_INSTANTATION_FUNC22(name,__m128) 
#else
#define EXPLICIT_INSTANTATION_FUNC22_ALL(name) \
EXPLICIT_INSTANTATION_FUNC22(name,double) \
EXPLICIT_INSTANTATION_FUNC22(name,float) \
EXPLICIT_INSTANTATION_FUNC22(name,__m256d) \
EXPLICIT_INSTANTATION_FUNC22(name,__m256) \
EXPLICIT_INSTANTATION_FUNC22(name,__m128d) \
EXPLICIT_INSTANTATION_FUNC22(name,__m128) 
#endif

#define EXPLICIT_INSTANTATION_FUNC23(name,T) \
template qscalar<T> VSGRAPH_API name(const qscalar<T>& lhs, const T& rhs);

#ifdef INSTANTIATE_AVX512
#define EXPLICIT_INSTANTATION_FUNC23_ALL(name) \
EXPLICIT_INSTANTATION_FUNC23(name,double) \
EXPLICIT_INSTANTATION_FUNC23(name,float) \
EXPLICIT_INSTANTATION_FUNC23(name,__m512d) \
EXPLICIT_INSTANTATION_FUNC23(name,__m512) \
EXPLICIT_INSTANTATION_FUNC23(name,__m256d) \
EXPLICIT_INSTANTATION_FUNC23(name,__m256) \
EXPLICIT_INSTANTATION_FUNC23(name,__m128d) \
EXPLICIT_INSTANTATION_FUNC23(name,__m128) 
#else
#define EXPLICIT_INSTANTATION_FUNC23_ALL(name) \
EXPLICIT_INSTANTATION_FUNC23(name,double) \
EXPLICIT_INSTANTATION_FUNC23(name,float) \
EXPLICIT_INSTANTATION_FUNC23(name,__m256d) \
EXPLICIT_INSTANTATION_FUNC23(name,__m256) \
EXPLICIT_INSTANTATION_FUNC23(name,__m128d) \
EXPLICIT_INSTANTATION_FUNC23(name,__m128) 
#endif

#define EXPLICIT_INSTANTATION_FUNC24(name,T) \
template qscalar<T> VSGRAPH_API name(const qnumber<typename number_traits<T>::type>& lhs, const qscalar<T>& rhs);

#ifdef INSTANTIATE_AVX512
#define EXPLICIT_INSTANTATION_FUNC24_ALL(name) \
EXPLICIT_INSTANTATION_FUNC24(name,double) \
EXPLICIT_INSTANTATION_FUNC24(name,float) \
EXPLICIT_INSTANTATION_FUNC24(name,__m512d) \
EXPLICIT_INSTANTATION_FUNC24(name,__m512) \
EXPLICIT_INSTANTATION_FUNC24(name,__m256d) \
EXPLICIT_INSTANTATION_FUNC24(name,__m256) \
EXPLICIT_INSTANTATION_FUNC24(name,__m128d) \
EXPLICIT_INSTANTATION_FUNC24(name,__m128) 
#else
#define EXPLICIT_INSTANTATION_FUNC24_ALL(name) \
EXPLICIT_INSTANTATION_FUNC24(name,double) \
EXPLICIT_INSTANTATION_FUNC24(name,float) \
EXPLICIT_INSTANTATION_FUNC24(name,__m256d) \
EXPLICIT_INSTANTATION_FUNC24(name,__m256) \
EXPLICIT_INSTANTATION_FUNC24(name,__m128d) \
EXPLICIT_INSTANTATION_FUNC24(name,__m128) 
#endif

#define EXPLICIT_INSTANTATION_FUNC25(name,T) \
template qscalar<T> VSGRAPH_API name(const T& lhs, const qscalar<T>& rhs);

#ifdef INSTANTIATE_AVX512
#define EXPLICIT_INSTANTATION_FUNC25_ALL(name) \
EXPLICIT_INSTANTATION_FUNC25(name,double) \
EXPLICIT_INSTANTATION_FUNC25(name,float) \
EXPLICIT_INSTANTATION_FUNC25(name,__m512d) \
EXPLICIT_INSTANTATION_FUNC25(name,__m512) \
EXPLICIT_INSTANTATION_FUNC25(name,__m256d) \
EXPLICIT_INSTANTATION_FUNC25(name,__m256) \
EXPLICIT_INSTANTATION_FUNC25(name,__m128d) \
EXPLICIT_INSTANTATION_FUNC25(name,__m128) 
#else
#define EXPLICIT_INSTANTATION_FUNC25_ALL(name) \
EXPLICIT_INSTANTATION_FUNC25(name,double) \
EXPLICIT_INSTANTATION_FUNC25(name,float) \
EXPLICIT_INSTANTATION_FUNC25(name,__m256d) \
EXPLICIT_INSTANTATION_FUNC25(name,__m256) \
EXPLICIT_INSTANTATION_FUNC25(name,__m128d) \
EXPLICIT_INSTANTATION_FUNC25(name,__m128) 
#endif


template<class T>
qrecorder_i<T>* recorder_ptr();


